# Use the official Node image
FROM node:18-alpine3.18

# Set the working directory in the container
WORKDIR /user/src/app

COPY package*.json ./

# Fetch dependencies
RUN npm install


# Copy the source code into the container
COPY . .

#RUN npm run build
#RUN npm install -g serve


# Expose the port
EXPOSE 3000

# Command to run the executable
CMD ["npm", "start"]
#CMD ["serve", "-s","build"]