# Use the official Node image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

#envshit
ENV FLASK_APP=main.py

ENV FLASK_ENV=development
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY ./requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install ffmpeg
RUN apt-get install -y ffmpeg


# Copy the source code into the container
COPY . .

# Expose the port
#EXPOSE 5000

# Command to run the executable
CMD ["python", "src/main.py"]
